---
title: Ahmet Altınışık's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: Notes on Odoo work
author: Ahmet Altinisik
email: aaltinisik@altinkaya.com.tr
description: Ahmet Altınışık's Blog on Odoo related work.
keywords: Odoo, Ahmet Altinisik, PostgreSQL
baseurl: ''
url: http://ahmet.altinisik.net
locale: en_US
twitter_username: AhmetAltinisik
github_username: aaltinisik
disqus_shortname: aaltinisik
favicon: "/images/favicon.ico"
aboutme: Hi, this is Ahmet Altinisik. I wrote my notes about odoo so to remember.
aboutme_photo: https://gravatar.com/avatar/982c05e4361870c8a413e3157914f526
google_analytics_key: UA-28213384-1
ShowContactInfo: 'False'
default_column: one
default_locale: en
locales:
  en:
    Aboutme: About Me
    Archives: Archives
    Blogroll: Blogroll
    Categories: Categories
    Copyright_Notice: Copyright Notice
    Recent_Posts: Recent Posts
    Tags: Tags
    Previous: Older
    Next: Newer
    PostedInCategories: Posted in
    Taggedwith: and tagged
    PostDate: 'on '
    Google_search: Site Search
  cn:
    Aboutme: "关于我"
    Archives: "存档"
    Blogroll: "良师益友"
    Categories: "分类目录"
    Copyright_Notice: "版权声明"
    Recent_Posts: "近期文章"
    Tags: "标签"
    Previous: "前一页"
    Next: "后一页"
    PostedInCategories: "目录:"
    Taggedwith: "| 标签:"
    PostDate: "| 发表时间: "
    Google_search: "站内搜索"
Blogroll:
- name: Blog
  href: http://ahmet.altinisik.net
  title: Ahmet Altinisik's Blog
- name: author's website
  href: http://www.altinkaya.eu/
  title: Altinkaya Enclosures For Electronics
markdown: kramdown
highlighter: pygments
gems:
- jekyll-paginate
paginate: 10
excerpt_separator: "<!-- more -->"
